/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TableIndexImport } from './routes/table/index'
import { Route as TableCreateImport } from './routes/table/create'
import { Route as TableIdEditImport } from './routes/table/$id.edit'

// Create/Update Routes

const TableIndexRoute = TableIndexImport.update({
  id: '/table/',
  path: '/table/',
  getParentRoute: () => rootRoute,
} as any)

const TableCreateRoute = TableCreateImport.update({
  id: '/table/create',
  path: '/table/create',
  getParentRoute: () => rootRoute,
} as any)

const TableIdEditRoute = TableIdEditImport.update({
  id: '/table/$id/edit',
  path: '/table/$id/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/table/create': {
      id: '/table/create'
      path: '/table/create'
      fullPath: '/table/create'
      preLoaderRoute: typeof TableCreateImport
      parentRoute: typeof rootRoute
    }
    '/table/': {
      id: '/table/'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableIndexImport
      parentRoute: typeof rootRoute
    }
    '/table/$id/edit': {
      id: '/table/$id/edit'
      path: '/table/$id/edit'
      fullPath: '/table/$id/edit'
      preLoaderRoute: typeof TableIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/table/create': typeof TableCreateRoute
  '/table': typeof TableIndexRoute
  '/table/$id/edit': typeof TableIdEditRoute
}

export interface FileRoutesByTo {
  '/table/create': typeof TableCreateRoute
  '/table': typeof TableIndexRoute
  '/table/$id/edit': typeof TableIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/table/create': typeof TableCreateRoute
  '/table/': typeof TableIndexRoute
  '/table/$id/edit': typeof TableIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/table/create' | '/table' | '/table/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/table/create' | '/table' | '/table/$id/edit'
  id: '__root__' | '/table/create' | '/table/' | '/table/$id/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  TableCreateRoute: typeof TableCreateRoute
  TableIndexRoute: typeof TableIndexRoute
  TableIdEditRoute: typeof TableIdEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  TableCreateRoute: TableCreateRoute,
  TableIndexRoute: TableIndexRoute,
  TableIdEditRoute: TableIdEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/table/create",
        "/table/",
        "/table/$id/edit"
      ]
    },
    "/table/create": {
      "filePath": "table/create.tsx"
    },
    "/table/": {
      "filePath": "table/index.tsx"
    },
    "/table/$id/edit": {
      "filePath": "table/$id.edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
